### ISSUE TITLE
failure of BN128 code within libsnark

### ISSUE THREAD

**Issue by zookozcash** [herumi/ate-pairing#10]
Dear ate-pairing maintainers:

Thank you for your contributions! We are using the BN128 curve within libsnark within the [Zcash project](https://github.com/zcash/zcash). Currently we're using the implementation called [`ALT_BN128` within libsnark](https://github.com/scipr-lab/libsnark/tree/master/src/algebra/curves/alt_bn128). If we try switching to using instead the one called [`BN128` within libsnark](https://github.com/scipr-lab/libsnark/tree/master/src/algebra/curves/bn128), we get a failure: https://github.com/scipr-lab/libsnark/issues/25

We don't yet know if this bug is introduced in libsnark or in some other implementations of the `BN128` code.

The reason we're testing using `BN128` within libsnark instead of `ALT_BN128` within libsnark is that the former may be more efficient for our use.

**Comment by herumi** [comment]
I will check it. Please wait a moment.

**Comment by herumi** [comment]
I found that Fp12::final_exp() runs well at my toy-example, but it returns bad value in libsnark when same values are given and I am investing the reason.
Please wait a little longer.

**Comment by herumi** [comment]
I'm sorry for the delay in my reply.
It is a simple reason.
Define `BN_SUPPORT_SNARK` if you use libsnark with bn128.
```
Makefile
@@ -1,6 +1,6 @@
 OPTFLAGS = -march=native -mtune=native -O2
 CXXFLAGS += -g -Wall -Wextra -Wno-unused-parameter -std=c++11 -fPIC -Wno-unused-variable
-CXXFLAGS += -I $(DEPINST)/include -I $(DEPINST)/include/libsnark -DUSE_ASM -DCURVE_ALT_BN128
+CXXFLAGS += -I $(DEPINST)/include -I $(DEPINST)/include/libsnark -DUSE_ASM -DCURVE_BN128 -DBN_SUPPORT_SNARK
```

**Comment by ebfull** [comment]
Thanks!

**Comment by daira** [comment]
Thanks. I see that ate-pairing's readme.md mentions ``SUPPORT_SNARK`` but not ``BN_SUPPORT_SNARK``.

**Comment by herumi** [comment]
`SUPPORT_SNARK=1` is for Makefile and `BN_SUPPORT_SNARK` is macro name for compiler.
