### ISSUE TITLE
test/bn segfaults when run, but not when run under GDB

### ISSUE THREAD

**Issue by brouhaha** [herumi/ate-pairing#11]
I'm trying to package xbyak , ate-pairing, and libsnark for Fedora Linux. I've patched xybak.h to define XBYAK_USE_MMAP_ALLOCATOR to avoid SELinux problems with executing from the heap.  I've built ate-paring using "make SUPPORT_SNARK=1".

When I run test/bn, I get this output:

SNARK b = 3
support SNARK

followed by a segmentation fault.

However, when I run it under gdb, it gives that output, the benchmark results, and exits normally.

I get the segmentation fault even if I make it without SUPPORT_SNARK=1.

I'm somewhat at a loss to figure out how to debug the problem. Any suggestions or help will be greatly appreciated.

**Comment by herumi** [comment]
XBYAK_USE_MMAP_ALLOCATOR is not to avoid SELinux problem and it is automatically defined.
I don't know SELinux, but I think gdb is allowed to run xbyak.
How about creating custom SELinux policy for the binary of libsnark with xbyak according to https://wiki.centos.org/HowTos/SELinux#head-faa96b3fdd922004cdb988c1989e56191c257c01 ?
