### ISSUE TITLE
Update key sizes

### ISSUE THREAD

**Issue by shalec** [herumi/ate-pairing#16]
As assumed in 2016 and suggested in 2017 [1], you should update the key sizes for that implementation. Maybe there is a way to add the KSS16 curve as well? Since that new theoretical suggestions for larger keys, BN is no longer competetive?

[1] https://eprint.iacr.org/2017/334

**Comment by herumi** [comment]
Yes, I know the paper, but the parameter of my ate-pairing has about 100-bit security, and it is still secure now.
I'm developing another BN pairing library [mcl](https://github.com/herumi/mcl/) and it supports 384-bit BN curve. I'm studying which is the best curve KSS, BLS and etc. and will implement it in the future.
