### ISSUE TITLE
Build without MIE_USE_X64ASM

### ISSUE THREAD

**Issue by xu-cheng** [herumi/ate-pairing#19]
Hi, I am trying to build ate-pairing without xbyak.  Therefore, I tried to build ate-pairing without defining MIE_USE_X64ASM. However, the build is not successful. 

```
$ make
make -C src
make[1]: Entering directory '/home/comp/chengxu/git/ate-pairing/src'
g++ -c zm2.cpp -o zm2.o -fPIC -O3 -fomit-frame-pointer -DNDEBUG -msse2 -mfpmath=sse -march=native -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith  -D_FILE_OFFSET_BITS=64 -DMIE_ATE_USE_GMP -I../src -I../../xbyak -I../include -m64
g++ -c zm.cpp -o zm.o -fPIC -O3 -fomit-frame-pointer -DNDEBUG -msse2 -mfpmath=sse -march=native -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith  -D_FILE_OFFSET_BITS=64 -DMIE_ATE_USE_GMP -I../src -I../../xbyak -I../include -m64
zm2.cpp: In static member function 'static void mie::Fp::setModulo(const Vuint&, int, bool, bool)':
zm2.cpp:3644:22: error: 'Xbyak' was not declared in this scope
   static std::vector<Xbyak::uint8> buf;
                      ^
zm2.cpp:3644:34: error: template argument 1 is invalid
   static std::vector<Xbyak::uint8> buf;
                                  ^
zm2.cpp:3644:34: error: template argument 2 is invalid
zm2.cpp:3645:7: error: request for member 'resize' in 'buf', which is of non-class type 'int'
   buf.resize(codeSize + dataSize + PageSize);
       ^
zm2.cpp:3646:3: error: 'Xbyak' is not a class or namespace
   Xbyak::uint8 *const codeAddr = Xbyak::CodeArray::getAlignedAddress(&buf[0], PageSize);
   ^
zm2.cpp:3646:17: error: expected primary-expression before 'const'
   Xbyak::uint8 *const codeAddr = Xbyak::CodeArray::getAlignedAddress(&buf[0], PageSize);
                 ^
zm2.cpp:3647:3: error: 'Xbyak' is not a class or namespace
   Xbyak::CodeArray::protect(codeAddr, codeSize, true);
   ^
zm2.cpp:3647:29: error: 'codeAddr' was not declared in this scope
   Xbyak::CodeArray::protect(codeAddr, codeSize, true);
                             ^
zm2.cpp:3648:12: error: 'Xbyak' is not a class or namespace
   s_data = Xbyak::CastTo<Data*>(codeAddr + codeSize);
            ^
zm2.cpp:3648:30: error: expected primary-expression before '*' token
   s_data = Xbyak::CastTo<Data*>(codeAddr + codeSize);
                              ^
zm2.cpp:3648:31: error: expected primary-expression before '>' token
   s_data = Xbyak::CastTo<Data*>(codeAddr + codeSize);
                               ^
zm2.cpp:3676:10: error: 'PairingCode' does not name a type
   static PairingCode code(codeSize, codeAddr);
          ^
zm2.cpp:3677:3: error: 'code' was not declared in this scope
   code.init(p_, mode, useMulx);
   ^
make[1]: *** [../common.mk:49: zm2.o] Error 1
make[1]: Leaving directory '/home/comp/chengxu/git/ate-pairing/src'
make: *** [Makefile:2: all] Error 2
```

The issue comes from the following codes, which uses xbyak but is not guarded by MIE_USE_X64ASM.
https://github.com/herumi/ate-pairing/blob/e69890125746cdaf25b5b51227d96678f76479fe/src/zm2.cpp#L3576-L3690

Would you mind to help me solving this issue? The reason that I need to use ate-pairing without xbyak is I want to port this library into [Intel SGX](https://en.wikipedia.org/wiki/Software_Guard_Extensions). In SGX, it is not allowed (at least I am not able to find a way) to execute code in dynamic memory, hence JIT cannot be used.

**Comment by herumi** [comment]
I do not test ate-pairing without MIE_USE_X64ASM.
If you want to compute a pairing without JIT then could you try [mcl](https://github.com/herumi/mcl)?
```
make MCL_USE_XBYAK=0
```

**Comment by xu-cheng** [comment]
Thanks for the advice. However, it seems that gmp is required for mcl, which is unfortunately unavailable in SGX environment. 

For your information, SGX is a secure enclave developed by Intel for the purpose of secure computation. It cannot load dynamic libraries. Everything has to be built statically with some special flags. Therefore, it is hard to port library as large as gmp. I was hoping that ate-pairing is self contained enough to be ported to SGX, but currently is blocked by the JIT.

**Comment by herumi** [comment]
mcl supports no gmp environments.

If you want to compute a pairing without any extra library, then see [Makefile](https://github.com/herumi/mcl/blob/master/Makefile#L286-L287).
By the way, I'm interested in SGX, so could you how to use a pairing if possible?

**Comment by xu-cheng** [comment]
Thanks. I finally make it work with a lot of hacks. If I can find some free time after I finish an immediate deadline, I will try to organize them and report back. But right now, some of my changes can be found at:

https://github.com/xu-cheng/mcl/tree/sgx
https://github.com/xu-cheng/cybozulib/tree/sgx

> By the way, I'm interested in SGX

FYI, the SGX SDK is available at https://github.com/intel/linux-sgx. You can find an SGX C++ program example in https://github.com/intel/linux-sgx/tree/master/SampleCode/Cxx11SGXDemo

In order to port the library to SGX, the system call is not allowed. That means I need to replace `printf` to some special SGX API call. Further, `iostream` and `sstream` are not allowed as they will load codes with IO system calls. Some of my dirty hacks are trying to disable `iostream`. It would be help a lot if `mcl` and `cybozulib` can support a flag like `CYBOZU_DONT_USE_STREAM`

Thanks again for your time and help. 😉
