### ISSUE TITLE
Xbyak has removed CastTo from bf.cpp

### ISSUE THREAD

**Issue by howardwu** [herumi/ate-pairing#20]
As of this commit https://github.com/herumi/xbyak/commit/afdb9fe9ff49a48fda3da72d46f45451f8d8e401 (on October 20, 2018), Xbyak has removed CastTo which is currently used in ate-pairing here:
https://github.com/herumi/ate-pairing/blob/e69890125746cdaf25b5b51227d96678f76479fe/src/zm2.cpp#L3648

For those installing xbyak to use ate-pairing, either the use of CastTo will need to removed or the installation of an older version of xbyak will be necessary.

**Comment by herumi** [comment]
Thank you for your information. I fixed xbyak (https://github.com/herumi/xbyak/commit/bc70e7e11ad37f207ece73330c5b72a55fef1ceb).
