### ISSUE TITLE
How to sample random values in the groups?

### ISSUE THREAD

**Issue by vusirikala** [herumi/ate-pairing#23]
I was going through the code and could not find any function for random sampling in various groups. 

How to sample a random value in range [1,r]? (r is order of the group)

Is there a way to sample a random group elements in the groups Ec1, Ec2, Fp12?  One way is to sample a random value in [1,r] and then perform exponentiation w.r.t a fixed base. But this reveals the discrete log of sampled point. Is there any function that samples group elements without revealing discrete log?

Does this library support pre-computation? Which functions perform pre-computation?

**Comment by herumi** [comment]
I'm sorry to miss the issue for a long time.
This library is not maintained, so please use [mcl](https://github.com/herumi/mcl).

```
using namespace mcl::bn;
initPairing(curveType);
Fr x;
x.setByCSPRNG(); // set x in [0, r)
G1 P;
G2 Q;
hashAndMapToG1(P, <random byte>, byteSize);
hashAndMapToG2(Q, <random byte>, byteSize);
Fp12 e;
pairing(e, P, Q);
```
There is no function to make a random element of Fp12.

**Comment by herumi** [comment]
Use `precomputeG2` to pre-computation for a fixed value of G2.

https://github.com/herumi/mcl/blob/master/test/bn_test.cpp#L186-L195
