### ISSUE TITLE
Error compiling /test/sample.cpp

### ISSUE THREAD

**Issue by TharOasis** [herumi/ate-pairing#9]
On compiling sample.cpp ($ g++ sample.cpp) we get the following error:

/tmp/ccfVLjyw.o: In function `mie::Fp::set(int)':
sample.cpp:(.text._ZN3mie2Fp3setEi[_ZN3mie2Fp3setEi]+0x109): undefined reference to `mie::Fp::mul'
sample.cpp:(.text._ZN3mie2Fp3setEi[_ZN3mie2Fp3setEi]+0x116): undefined reference to `mie::Fp::montgomeryR2_'
sample.cpp:(.text._ZN3mie2Fp3setEi[_ZN3mie2Fp3setEi]+0x159): undefined reference to `mie::Fp::mul'
sample.cpp:(.text._ZN3mie2Fp3setEi[_ZN3mie2Fp3setEi]+0x166): undefined reference to `mie::Fp::montgomeryR2_'
sample.cpp:(.text._ZN3mie2Fp3setEi[_ZN3mie2Fp3setEi]+0x172): undefined reference to `mie::Fp::neg'
/tmp/ccfVLjyw.o: In function `mie::Fp::_3z_add_2xC(mie::Fp&, mie::Fp const&)':
sample.cpp:(.text._ZN3mie2Fp11_3z_add_2xCERS0_RKS0_[_ZN3mie2Fp11_3z_add_2xCERS0_RKS0_]+0x13): undefined reference to `mie::Fp::addNC'
sample.cpp:(.text._ZN3mie2Fp11_3z_add_2xCERS0_RKS0_[_ZN3mie2Fp11_3z_add_2xCERS0_RKS0_]+0x2b): undefined reference to `mie::Fp::addNC'
sample.cpp:(.text._ZN3mie2Fp11_3z_add_2xCERS0_RKS0_[_ZN3mie2Fp11_3z_add_2xCERS0_RKS0_]+0x43): undefined reference to `mie::Fp::addNC'
.
.
.
sample.cpp:(.text._ZN3mie6VuintTINS_5local11FixedBufferImLm576EEEE6sub_inERS4_RKS4_S7_[_ZN3mie6VuintTINS_5local11FixedBufferImLm576EEEE6sub_inERS4_RKS4_S7_]+0xd3): undefined reference to `mie::local::PrimitiveFunction::sub1'
collect2: error: ld returned 1 exit status

**Comment by herumi** [comment]
There is no error on my environments(eg. g++ 4.8.4 or clang++-3.6 on Ubuntu 14.04).
What version is your gcc?
By the way, do you type only `g++ sample.cpp`?
It is necessary to link lib/libzm.a like as
```
<ate-pairing>% g++ test/sample.cpp -I ./include ./lib/libzm.a
or
<ate-pairing>/test>% g++ test/sample.cpp -I ./include -L ./lib -lzm
```
Or type
```
<ate-pairing>% make
```
then `test/sample` will be created.

**Comment by TharOasis** [comment]
It's working fine now. Thanks for your time.

**Comment by herumi** [comment]
ok
